import type { NextPage } from "next";
import { Col, Row } from "antd";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { LabelBottom, TextBold, TextBoldLight, TextGrey } from "../src/components/styles";
import GrabMono from "../assets/icon/grab-monoo.svg";
import SocialIcon from "../assets/icon/socialicon.png";
import PlayStore from "../assets/icon/logo-playstore.svg";
import AppStore from "../assets/icon/logo-appstore.svg";
import Header from "../src/components/header/Header";
import HeaderContainer from "../src/components/headerContainer/HeaderContainer";
import Tabs from "../src/components/Tabs/Tabs";
import { menuData } from "../src/mocks/menu";
import LinksUnderline from "../src/components/links/LinkUnderline";
import InstagramFilled from "@ant-design/icons/InstagramFilled";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container} style={{ background: "#f7f7f7" }}>
        <Header />
       
          <HeaderContainer />
          <Tabs />
          <LabelBottom>
            We`re always working to get the most accurate information. Let us
            know if you come across anything thats outdated!
          </LabelBottom>

      </div>
      <footer>
        <div className={styles.footerContainer}>
          <Image alt="mono" src={GrabMono} />
          <div className={styles.footer} style={{ marginTop: 30 }}>
            <Row>
              <Col span={6}>
                <TextBold>Frequently Searched</TextBold>
                {menuData[0].map((val, i) => (
                  <LinksUnderline key={i} text={val.toString()} />
                ))}
              </Col>
              <Col span={6}>
                <TextBold>Popular Cuisines</TextBold>
                {menuData[1].map((val, i) => (
                  <LinksUnderline key={i} text={val.toString()} />
                ))}
              </Col>
              <Col span={6}>
                {" "}
                <TextBold>About Grab</TextBold>
                {menuData[2].map((val, i) => (
                  <LinksUnderline key={i} text={val.toString()} />
                ))}
              </Col>
              <Col span={6}>
                {" "}
                <TextBold>Support</TextBold>
                {menuData[3].map((val, i) => (
                  <LinksUnderline key={i} text={val.toString()} />
                ))}
              </Col>
            </Row>
          </div>
        </div>

        <div className={styles.footerBottom} style={{ background: "#363a45" }}>
          <Row>
            <Col span={12}>
              <TextBoldLight>Countries with GrabFood</TextBoldLight>
            </Col>
            <Col span={12} style={{ textAlign: "right" }}>
              {" "}
              <Image
                src={SocialIcon}
                alt="social Icon"
                height={47}
                width={168}
              />
            </Col>
          </Row>
          <Row>
            <Row>
              <a href="#" style={{ color: "white" }}>
                Indonesia |
              </a>
              <a href="#" style={{ color: "white" }}>
                Philipiness |
              </a>
              <a href="#" style={{ color: "white" }}>
                Thailand |
              </a>
              <a href="#" style={{ color: "white" }}>
                Vietnam |
              </a>
              <a href="#" style={{ color: "white" }}>
                Singapore |
              </a>
              <a href="#" style={{ color: "white" }}>
                Malaysia |
              </a>
              <a href="#" style={{ color: "white" }}>
                Myanmar |
              </a>
            </Row>
            <Col span={12}></Col>
          </Row>
          <Row>
            <Col span={12}>
              <TextBoldLight>
                <TextGrey>© Grab 2022</TextGrey>
              </TextBoldLight>
            </Col>
            <Col span={12}></Col>
          </Row>
          <Row>
            <Col span={12}>
              <TextBoldLight>Terms of Service•Privacy Policy</TextBoldLight>
            </Col>
            <Col span={12} style={{ textAlign: "right" }}>
              <Image style={{ paddingRight: 30 }} alt="mono" src={AppStore} />
              <Image style={{ paddingLeft: 30 }} alt="mono" src={PlayStore} />
            </Col>
          </Row>
          <div style={{ display: "flex", flexDirection: "column" }}>
            <div style={{ display: "flex", flexDirection: "column" }}></div>
            <div style={{ flexDirection: "row" }}></div>
          </div>
        </div>
      </footer>
    </div>
  );
};

export default Home;
